FROM itzg/minecraft-server:java8

ENV EULA=TRUE
ENV VERSION=1.16.5
ENV TYPE=FORGE
ENV MODE=creative
ENV SERVER_NAME="Felix's Forge Minecraft Server"
ENV PVP=false
ENV DIFFICULTY=normal
ENV LEVEL_TYPE=DEFAULT
ENV OPS=FormableSteak84,AmbigousTuna428
ENV MEMORY=2G

EXPOSE 25565
